# Generated by Django 5.0.4 on 2024-04-12 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_urls_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='link',
            field=models.CharField(default=1, max_length=10000),
        ),
    ]
